// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/proto/loan_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationType int32

const (
	ApplicationType_APPLICATION_TYPE_UNSPECIFIED ApplicationType = 0
	ApplicationType_APPLICATION_TYPE_AUTO        ApplicationType = 1
	ApplicationType_APPLICATION_TYPE_PERSONAL    ApplicationType = 2
)

// Enum value maps for ApplicationType.
var (
	ApplicationType_name = map[int32]string{
		0: "APPLICATION_TYPE_UNSPECIFIED",
		1: "APPLICATION_TYPE_AUTO",
		2: "APPLICATION_TYPE_PERSONAL",
	}
	ApplicationType_value = map[string]int32{
		"APPLICATION_TYPE_UNSPECIFIED": 0,
		"APPLICATION_TYPE_AUTO":        1,
		"APPLICATION_TYPE_PERSONAL":    2,
	}
)

func (x ApplicationType) Enum() *ApplicationType {
	p := new(ApplicationType)
	*p = x
	return p
}

func (x ApplicationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplicationType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_loan_service_proto_enumTypes[0].Descriptor()
}

func (ApplicationType) Type() protoreflect.EnumType {
	return &file_internal_proto_loan_service_proto_enumTypes[0]
}

func (x ApplicationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplicationType.Descriptor instead.
func (ApplicationType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{0}
}

type ApplicationStatus int32

const (
	ApplicationStatus_APPLICATION_STATUS_UNSPECIFIED ApplicationStatus = 0
	ApplicationStatus_APPLICATION_STATUS_NEW         ApplicationStatus = 1
	ApplicationStatus_APPLICATION_STATUS_REVIEW      ApplicationStatus = 2
	ApplicationStatus_APPLICATION_STATUS_APPROVED    ApplicationStatus = 3
	ApplicationStatus_APPLICATION_STATUS_REJECTED    ApplicationStatus = 4
)

// Enum value maps for ApplicationStatus.
var (
	ApplicationStatus_name = map[int32]string{
		0: "APPLICATION_STATUS_UNSPECIFIED",
		1: "APPLICATION_STATUS_NEW",
		2: "APPLICATION_STATUS_REVIEW",
		3: "APPLICATION_STATUS_APPROVED",
		4: "APPLICATION_STATUS_REJECTED",
	}
	ApplicationStatus_value = map[string]int32{
		"APPLICATION_STATUS_UNSPECIFIED": 0,
		"APPLICATION_STATUS_NEW":         1,
		"APPLICATION_STATUS_REVIEW":      2,
		"APPLICATION_STATUS_APPROVED":    3,
		"APPLICATION_STATUS_REJECTED":    4,
	}
)

func (x ApplicationStatus) Enum() *ApplicationStatus {
	p := new(ApplicationStatus)
	*p = x
	return p
}

func (x ApplicationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplicationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_loan_service_proto_enumTypes[1].Descriptor()
}

func (ApplicationStatus) Type() protoreflect.EnumType {
	return &file_internal_proto_loan_service_proto_enumTypes[1]
}

func (x ApplicationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplicationStatus.Descriptor instead.
func (ApplicationStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{1}
}

type LoanStatus int32

const (
	LoanStatus_LOAN_STATUS_UNSPECIFIED LoanStatus = 0
	LoanStatus_LOAN_STATUS_ACTIVE      LoanStatus = 1
	LoanStatus_LOAN_STATUS_PAID        LoanStatus = 2
	LoanStatus_LOAN_STATUS_OVERDUE     LoanStatus = 3
)

// Enum value maps for LoanStatus.
var (
	LoanStatus_name = map[int32]string{
		0: "LOAN_STATUS_UNSPECIFIED",
		1: "LOAN_STATUS_ACTIVE",
		2: "LOAN_STATUS_PAID",
		3: "LOAN_STATUS_OVERDUE",
	}
	LoanStatus_value = map[string]int32{
		"LOAN_STATUS_UNSPECIFIED": 0,
		"LOAN_STATUS_ACTIVE":      1,
		"LOAN_STATUS_PAID":        2,
		"LOAN_STATUS_OVERDUE":     3,
	}
)

func (x LoanStatus) Enum() *LoanStatus {
	p := new(LoanStatus)
	*p = x
	return p
}

func (x LoanStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoanStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_loan_service_proto_enumTypes[2].Descriptor()
}

func (LoanStatus) Type() protoreflect.EnumType {
	return &file_internal_proto_loan_service_proto_enumTypes[2]
}

func (x LoanStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoanStatus.Descriptor instead.
func (LoanStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{2}
}

type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED PaymentMethod = 0
	PaymentMethod_PAYMENT_METHOD_WALLET      PaymentMethod = 1
	PaymentMethod_PAYMENT_METHOD_CARD        PaymentMethod = 2
	PaymentMethod_PAYMENT_METHOD_QR          PaymentMethod = 3
	PaymentMethod_PAYMENT_METHOD_AUTOPAY     PaymentMethod = 4
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "PAYMENT_METHOD_WALLET",
		2: "PAYMENT_METHOD_CARD",
		3: "PAYMENT_METHOD_QR",
		4: "PAYMENT_METHOD_AUTOPAY",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED": 0,
		"PAYMENT_METHOD_WALLET":      1,
		"PAYMENT_METHOD_CARD":        2,
		"PAYMENT_METHOD_QR":          3,
		"PAYMENT_METHOD_AUTOPAY":     4,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_loan_service_proto_enumTypes[3].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_internal_proto_loan_service_proto_enumTypes[3]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{3}
}

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_CONFIRMED   PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 3
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_CONFIRMED",
		3: "PAYMENT_STATUS_FAILED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_CONFIRMED":   2,
		"PAYMENT_STATUS_FAILED":      3,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_loan_service_proto_enumTypes[4].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_internal_proto_loan_service_proto_enumTypes[4]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{4}
}

type LoanServiceError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanServiceError) Reset() {
	*x = LoanServiceError{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanServiceError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanServiceError) ProtoMessage() {}

func (x *LoanServiceError) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanServiceError.ProtoReflect.Descriptor instead.
func (*LoanServiceError) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{0}
}

func (x *LoanServiceError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoanServiceError) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// -------------------- Core models --------------------
type Vehicle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vin           string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	CurrencyCode  string                 `protobuf:"bytes,4,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"` // "TJS", "USD"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{1}
}

func (x *Vehicle) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *Vehicle) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Vehicle) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Vehicle) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

type LoanApplication struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type           ApplicationType        `protobuf:"varint,3,opt,name=type,proto3,enum=proto.ApplicationType" json:"type,omitempty"`
	VehicleVin     string                 `protobuf:"bytes,4,opt,name=vehicle_vin,json=vehicleVin,proto3" json:"vehicle_vin,omitempty"`
	VehicleName    string                 `protobuf:"bytes,5,opt,name=vehicle_name,json=vehicleName,proto3" json:"vehicle_name,omitempty"`
	CurrencyCode   string                 `protobuf:"bytes,6,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	Price          int64                  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	DownPayment    int64                  `protobuf:"varint,8,opt,name=down_payment,json=downPayment,proto3" json:"down_payment,omitempty"`
	NetPrice       int64                  `protobuf:"varint,9,opt,name=net_price,json=netPrice,proto3" json:"net_price,omitempty"`
	MarginRate     float64                `protobuf:"fixed64,10,opt,name=margin_rate,json=marginRate,proto3" json:"margin_rate,omitempty"`
	TermMonths     int32                  `protobuf:"varint,11,opt,name=term_months,json=termMonths,proto3" json:"term_months,omitempty"`
	MonthlyPayment int64                  `protobuf:"varint,12,opt,name=monthly_payment,json=monthlyPayment,proto3" json:"monthly_payment,omitempty"`
	Status         ApplicationStatus      `protobuf:"varint,13,opt,name=status,proto3,enum=proto.ApplicationStatus" json:"status,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoanApplication) Reset() {
	*x = LoanApplication{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanApplication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanApplication) ProtoMessage() {}

func (x *LoanApplication) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanApplication.ProtoReflect.Descriptor instead.
func (*LoanApplication) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{2}
}

func (x *LoanApplication) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoanApplication) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoanApplication) GetType() ApplicationType {
	if x != nil {
		return x.Type
	}
	return ApplicationType_APPLICATION_TYPE_UNSPECIFIED
}

func (x *LoanApplication) GetVehicleVin() string {
	if x != nil {
		return x.VehicleVin
	}
	return ""
}

func (x *LoanApplication) GetVehicleName() string {
	if x != nil {
		return x.VehicleName
	}
	return ""
}

func (x *LoanApplication) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *LoanApplication) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *LoanApplication) GetDownPayment() int64 {
	if x != nil {
		return x.DownPayment
	}
	return 0
}

func (x *LoanApplication) GetNetPrice() int64 {
	if x != nil {
		return x.NetPrice
	}
	return 0
}

func (x *LoanApplication) GetMarginRate() float64 {
	if x != nil {
		return x.MarginRate
	}
	return 0
}

func (x *LoanApplication) GetTermMonths() int32 {
	if x != nil {
		return x.TermMonths
	}
	return 0
}

func (x *LoanApplication) GetMonthlyPayment() int64 {
	if x != nil {
		return x.MonthlyPayment
	}
	return 0
}

func (x *LoanApplication) GetStatus() ApplicationStatus {
	if x != nil {
		return x.Status
	}
	return ApplicationStatus_APPLICATION_STATUS_UNSPECIFIED
}

func (x *LoanApplication) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *LoanApplication) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Loan struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId    string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	UserId           string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrencyCode     string                 `protobuf:"bytes,4,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	VehicleVin       string                 `protobuf:"bytes,5,opt,name=vehicle_vin,json=vehicleVin,proto3" json:"vehicle_vin,omitempty"`
	Amount           int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	TermMonths       int32                  `protobuf:"varint,7,opt,name=term_months,json=termMonths,proto3" json:"term_months,omitempty"`
	MonthlyPayment   int64                  `protobuf:"varint,8,opt,name=monthly_payment,json=monthlyPayment,proto3" json:"monthly_payment,omitempty"`
	RemainingBalance int64                  `protobuf:"varint,9,opt,name=remaining_balance,json=remainingBalance,proto3" json:"remaining_balance,omitempty"`
	Status           LoanStatus             `protobuf:"varint,10,opt,name=status,proto3,enum=proto.LoanStatus" json:"status,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Loan) Reset() {
	*x = Loan{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Loan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Loan) ProtoMessage() {}

func (x *Loan) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Loan.ProtoReflect.Descriptor instead.
func (*Loan) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{3}
}

func (x *Loan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Loan) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *Loan) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Loan) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *Loan) GetVehicleVin() string {
	if x != nil {
		return x.VehicleVin
	}
	return ""
}

func (x *Loan) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Loan) GetTermMonths() int32 {
	if x != nil {
		return x.TermMonths
	}
	return 0
}

func (x *Loan) GetMonthlyPayment() int64 {
	if x != nil {
		return x.MonthlyPayment
	}
	return 0
}

func (x *Loan) GetRemainingBalance() int64 {
	if x != nil {
		return x.RemainingBalance
	}
	return 0
}

func (x *Loan) GetStatus() LoanStatus {
	if x != nil {
		return x.Status
	}
	return LoanStatus_LOAN_STATUS_UNSPECIFIED
}

func (x *Loan) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LoanId        string                 `protobuf:"bytes,2,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	CurrencyCode  string                 `protobuf:"bytes,3,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	PaymentDate   string                 `protobuf:"bytes,4,opt,name=payment_date,json=paymentDate,proto3" json:"payment_date,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Method        PaymentMethod          `protobuf:"varint,6,opt,name=method,proto3,enum=proto.PaymentMethod" json:"method,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=proto.PaymentStatus" json:"status,omitempty"`
	TransactionId string                 `protobuf:"bytes,8,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{4}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

func (x *Payment) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *Payment) GetPaymentDate() string {
	if x != nil {
		return x.PaymentDate
	}
	return ""
}

func (x *Payment) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *Payment) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *Payment) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Payment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{5}
}

func (x *PageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	TotalItems    int32                  `protobuf:"varint,3,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{6}
}

func (x *PageResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *PageResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PageResponse) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *PageResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// Application
type CreateApplicationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type             ApplicationType        `protobuf:"varint,2,opt,name=type,proto3,enum=proto.ApplicationType" json:"type,omitempty"`
	VehicleVin       string                 `protobuf:"bytes,3,opt,name=vehicle_vin,json=vehicleVin,proto3" json:"vehicle_vin,omitempty"`
	VehicleName      string                 `protobuf:"bytes,4,opt,name=vehicle_name,json=vehicleName,proto3" json:"vehicle_name,omitempty"`
	CurrencyCode     string                 `protobuf:"bytes,5,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	PriceMinor       int64                  `protobuf:"varint,6,opt,name=price_minor,json=priceMinor,proto3" json:"price_minor,omitempty"`
	DownPaymentMinor int64                  `protobuf:"varint,7,opt,name=down_payment_minor,json=downPaymentMinor,proto3" json:"down_payment_minor,omitempty"`
	TermMonths       int32                  `protobuf:"varint,8,opt,name=term_months,json=termMonths,proto3" json:"term_months,omitempty"`
	MarginRate       float64                `protobuf:"fixed64,9,opt,name=margin_rate,json=marginRate,proto3" json:"margin_rate,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateApplicationRequest) Reset() {
	*x = CreateApplicationRequest{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationRequest) ProtoMessage() {}

func (x *CreateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationRequest.ProtoReflect.Descriptor instead.
func (*CreateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateApplicationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateApplicationRequest) GetType() ApplicationType {
	if x != nil {
		return x.Type
	}
	return ApplicationType_APPLICATION_TYPE_UNSPECIFIED
}

func (x *CreateApplicationRequest) GetVehicleVin() string {
	if x != nil {
		return x.VehicleVin
	}
	return ""
}

func (x *CreateApplicationRequest) GetVehicleName() string {
	if x != nil {
		return x.VehicleName
	}
	return ""
}

func (x *CreateApplicationRequest) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *CreateApplicationRequest) GetPriceMinor() int64 {
	if x != nil {
		return x.PriceMinor
	}
	return 0
}

func (x *CreateApplicationRequest) GetDownPaymentMinor() int64 {
	if x != nil {
		return x.DownPaymentMinor
	}
	return 0
}

func (x *CreateApplicationRequest) GetTermMonths() int32 {
	if x != nil {
		return x.TermMonths
	}
	return 0
}

func (x *CreateApplicationRequest) GetMarginRate() float64 {
	if x != nil {
		return x.MarginRate
	}
	return 0
}

type CreateApplicationResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Application      *LoanApplication       `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	LoanServiceError *LoanServiceError      `protobuf:"bytes,100,opt,name=loan_service_error,json=loanServiceError,proto3" json:"loan_service_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateApplicationResponse) Reset() {
	*x = CreateApplicationResponse{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationResponse) ProtoMessage() {}

func (x *CreateApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationResponse.ProtoReflect.Descriptor instead.
func (*CreateApplicationResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateApplicationResponse) GetApplication() *LoanApplication {
	if x != nil {
		return x.Application
	}
	return nil
}

func (x *CreateApplicationResponse) GetLoanServiceError() *LoanServiceError {
	if x != nil {
		return x.LoanServiceError
	}
	return nil
}

type GetApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationRequest) Reset() {
	*x = GetApplicationRequest{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationRequest) ProtoMessage() {}

func (x *GetApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetApplicationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetApplicationResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Application      *LoanApplication       `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	LoanServiceError *LoanServiceError      `protobuf:"bytes,100,opt,name=loan_service_error,json=loanServiceError,proto3" json:"loan_service_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetApplicationResponse) Reset() {
	*x = GetApplicationResponse{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationResponse) ProtoMessage() {}

func (x *GetApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationResponse.ProtoReflect.Descriptor instead.
func (*GetApplicationResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetApplicationResponse) GetApplication() *LoanApplication {
	if x != nil {
		return x.Application
	}
	return nil
}

func (x *GetApplicationResponse) GetLoanServiceError() *LoanServiceError {
	if x != nil {
		return x.LoanServiceError
	}
	return nil
}

type ListApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsRequest) Reset() {
	*x = ListApplicationsRequest{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsRequest) ProtoMessage() {}

func (x *ListApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListApplicationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListApplicationsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListApplicationsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Applications     []*LoanApplication     `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	Page             *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	LoanServiceError *LoanServiceError      `protobuf:"bytes,100,opt,name=loan_service_error,json=loanServiceError,proto3" json:"loan_service_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListApplicationsResponse) Reset() {
	*x = ListApplicationsResponse{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsResponse) ProtoMessage() {}

func (x *ListApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsResponse.ProtoReflect.Descriptor instead.
func (*ListApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListApplicationsResponse) GetApplications() []*LoanApplication {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *ListApplicationsResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListApplicationsResponse) GetLoanServiceError() *LoanServiceError {
	if x != nil {
		return x.LoanServiceError
	}
	return nil
}

type ListVehiclesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesRequest) Reset() {
	*x = ListVehiclesRequest{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesRequest) ProtoMessage() {}

func (x *ListVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesRequest.ProtoReflect.Descriptor instead.
func (*ListVehiclesRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{13}
}

type ListVehiclesResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Vehicles         []*Vehicle             `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	LoanServiceError *LoanServiceError      `protobuf:"bytes,100,opt,name=loan_service_error,json=loanServiceError,proto3" json:"loan_service_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListVehiclesResponse) Reset() {
	*x = ListVehiclesResponse{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesResponse) ProtoMessage() {}

func (x *ListVehiclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesResponse.ProtoReflect.Descriptor instead.
func (*ListVehiclesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListVehiclesResponse) GetVehicles() []*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

func (x *ListVehiclesResponse) GetLoanServiceError() *LoanServiceError {
	if x != nil {
		return x.LoanServiceError
	}
	return nil
}

// Calculator
type CalculateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CurrencyCode     string                 `protobuf:"bytes,1,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	PriceMinor       int64                  `protobuf:"varint,2,opt,name=price_minor,json=priceMinor,proto3" json:"price_minor,omitempty"`
	DownPaymentMinor int64                  `protobuf:"varint,3,opt,name=down_payment_minor,json=downPaymentMinor,proto3" json:"down_payment_minor,omitempty"`
	TermMonths       int32                  `protobuf:"varint,4,opt,name=term_months,json=termMonths,proto3" json:"term_months,omitempty"`
	MarginRate       float64                `protobuf:"fixed64,5,opt,name=margin_rate,json=marginRate,proto3" json:"margin_rate,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CalculateRequest) Reset() {
	*x = CalculateRequest{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRequest) ProtoMessage() {}

func (x *CalculateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRequest.ProtoReflect.Descriptor instead.
func (*CalculateRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{15}
}

func (x *CalculateRequest) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *CalculateRequest) GetPriceMinor() int64 {
	if x != nil {
		return x.PriceMinor
	}
	return 0
}

func (x *CalculateRequest) GetDownPaymentMinor() int64 {
	if x != nil {
		return x.DownPaymentMinor
	}
	return 0
}

func (x *CalculateRequest) GetTermMonths() int32 {
	if x != nil {
		return x.TermMonths
	}
	return 0
}

func (x *CalculateRequest) GetMarginRate() float64 {
	if x != nil {
		return x.MarginRate
	}
	return 0
}

type CalculateResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NetPriceMinor       int64                  `protobuf:"varint,1,opt,name=net_price_minor,json=netPriceMinor,proto3" json:"net_price_minor,omitempty"`
	MonthlyPaymentMinor int64                  `protobuf:"varint,2,opt,name=monthly_payment_minor,json=monthlyPaymentMinor,proto3" json:"monthly_payment_minor,omitempty"`
	TotalAmountMinor    int64                  `protobuf:"varint,3,opt,name=total_amount_minor,json=totalAmountMinor,proto3" json:"total_amount_minor,omitempty"`
	LoanServiceError    *LoanServiceError      `protobuf:"bytes,100,opt,name=loan_service_error,json=loanServiceError,proto3" json:"loan_service_error,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CalculateResponse) Reset() {
	*x = CalculateResponse{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateResponse) ProtoMessage() {}

func (x *CalculateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateResponse.ProtoReflect.Descriptor instead.
func (*CalculateResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{16}
}

func (x *CalculateResponse) GetNetPriceMinor() int64 {
	if x != nil {
		return x.NetPriceMinor
	}
	return 0
}

func (x *CalculateResponse) GetMonthlyPaymentMinor() int64 {
	if x != nil {
		return x.MonthlyPaymentMinor
	}
	return 0
}

func (x *CalculateResponse) GetTotalAmountMinor() int64 {
	if x != nil {
		return x.TotalAmountMinor
	}
	return 0
}

func (x *CalculateResponse) GetLoanServiceError() *LoanServiceError {
	if x != nil {
		return x.LoanServiceError
	}
	return nil
}

// Loans
type GetLoanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoanRequest) Reset() {
	*x = GetLoanRequest{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanRequest) ProtoMessage() {}

func (x *GetLoanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanRequest.ProtoReflect.Descriptor instead.
func (*GetLoanRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetLoanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetLoanResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Loan             *Loan                  `protobuf:"bytes,1,opt,name=loan,proto3" json:"loan,omitempty"`
	LoanServiceError *LoanServiceError      `protobuf:"bytes,100,opt,name=loan_service_error,json=loanServiceError,proto3" json:"loan_service_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetLoanResponse) Reset() {
	*x = GetLoanResponse{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanResponse) ProtoMessage() {}

func (x *GetLoanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanResponse.ProtoReflect.Descriptor instead.
func (*GetLoanResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetLoanResponse) GetLoan() *Loan {
	if x != nil {
		return x.Loan
	}
	return nil
}

func (x *GetLoanResponse) GetLoanServiceError() *LoanServiceError {
	if x != nil {
		return x.LoanServiceError
	}
	return nil
}

type ListLoansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoansRequest) Reset() {
	*x = ListLoansRequest{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoansRequest) ProtoMessage() {}

func (x *ListLoansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoansRequest.ProtoReflect.Descriptor instead.
func (*ListLoansRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{19}
}

func (x *ListLoansRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListLoansRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListLoansResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Loans            []*Loan                `protobuf:"bytes,1,rep,name=loans,proto3" json:"loans,omitempty"`
	Page             *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	LoanServiceError *LoanServiceError      `protobuf:"bytes,100,opt,name=loan_service_error,json=loanServiceError,proto3" json:"loan_service_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListLoansResponse) Reset() {
	*x = ListLoansResponse{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoansResponse) ProtoMessage() {}

func (x *ListLoansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoansResponse.ProtoReflect.Descriptor instead.
func (*ListLoansResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{20}
}

func (x *ListLoansResponse) GetLoans() []*Loan {
	if x != nil {
		return x.Loans
	}
	return nil
}

func (x *ListLoansResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListLoansResponse) GetLoanServiceError() *LoanServiceError {
	if x != nil {
		return x.LoanServiceError
	}
	return nil
}

// Payments
type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanId        string                 `protobuf:"bytes,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	CurrencyCode  string                 `protobuf:"bytes,2,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Method        PaymentMethod          `protobuf:"varint,4,opt,name=method,proto3,enum=proto.PaymentMethod" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{21}
}

func (x *CreatePaymentRequest) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

func (x *CreatePaymentRequest) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentRequest) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

type CreatePaymentResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Payment          *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	LoanServiceError *LoanServiceError      `protobuf:"bytes,100,opt,name=loan_service_error,json=loanServiceError,proto3" json:"loan_service_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{22}
}

func (x *CreatePaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *CreatePaymentResponse) GetLoanServiceError() *LoanServiceError {
	if x != nil {
		return x.LoanServiceError
	}
	return nil
}

type ListPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanId        string                 `protobuf:"bytes,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsRequest) Reset() {
	*x = ListPaymentsRequest{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsRequest) ProtoMessage() {}

func (x *ListPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{23}
}

func (x *ListPaymentsRequest) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

func (x *ListPaymentsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListPaymentsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Payments         []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	Page             *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	LoanServiceError *LoanServiceError      `protobuf:"bytes,100,opt,name=loan_service_error,json=loanServiceError,proto3" json:"loan_service_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListPaymentsResponse) Reset() {
	*x = ListPaymentsResponse{}
	mi := &file_internal_proto_loan_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsResponse) ProtoMessage() {}

func (x *ListPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_service_proto_rawDescGZIP(), []int{24}
}

func (x *ListPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *ListPaymentsResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListPaymentsResponse) GetLoanServiceError() *LoanServiceError {
	if x != nil {
		return x.LoanServiceError
	}
	return nil
}

var File_internal_proto_loan_service_proto protoreflect.FileDescriptor

const file_internal_proto_loan_service_proto_rawDesc = "" +
	"\n" +
	"!internal/proto/loan_service.proto\x12\x05proto\"H\n" +
	"\x10LoanServiceError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"j\n" +
	"\aVehicle\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12#\n" +
	"\rcurrency_code\x18\x04 \x01(\tR\fcurrencyCode\"\x80\x04\n" +
	"\x0fLoanApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12*\n" +
	"\x04type\x18\x03 \x01(\x0e2\x16.proto.ApplicationTypeR\x04type\x12\x1f\n" +
	"\vvehicle_vin\x18\x04 \x01(\tR\n" +
	"vehicleVin\x12!\n" +
	"\fvehicle_name\x18\x05 \x01(\tR\vvehicleName\x12#\n" +
	"\rcurrency_code\x18\x06 \x01(\tR\fcurrencyCode\x12\x14\n" +
	"\x05price\x18\a \x01(\x03R\x05price\x12!\n" +
	"\fdown_payment\x18\b \x01(\x03R\vdownPayment\x12\x1b\n" +
	"\tnet_price\x18\t \x01(\x03R\bnetPrice\x12\x1f\n" +
	"\vmargin_rate\x18\n" +
	" \x01(\x01R\n" +
	"marginRate\x12\x1f\n" +
	"\vterm_months\x18\v \x01(\x05R\n" +
	"termMonths\x12'\n" +
	"\x0fmonthly_payment\x18\f \x01(\x03R\x0emonthlyPayment\x120\n" +
	"\x06status\x18\r \x01(\x0e2\x18.proto.ApplicationStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt\"\xf5\x02\n" +
	"\x04Loan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12#\n" +
	"\rcurrency_code\x18\x04 \x01(\tR\fcurrencyCode\x12\x1f\n" +
	"\vvehicle_vin\x18\x05 \x01(\tR\n" +
	"vehicleVin\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\x12\x1f\n" +
	"\vterm_months\x18\a \x01(\x05R\n" +
	"termMonths\x12'\n" +
	"\x0fmonthly_payment\x18\b \x01(\x03R\x0emonthlyPayment\x12+\n" +
	"\x11remaining_balance\x18\t \x01(\x03R\x10remainingBalance\x12)\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x11.proto.LoanStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\"\xb4\x02\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aloan_id\x18\x02 \x01(\tR\x06loanId\x12#\n" +
	"\rcurrency_code\x18\x03 \x01(\tR\fcurrencyCode\x12!\n" +
	"\fpayment_date\x18\x04 \x01(\tR\vpaymentDate\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12,\n" +
	"\x06method\x18\x06 \x01(\x0e2\x14.proto.PaymentMethodR\x06method\x12,\n" +
	"\x06status\x18\a \x01(\x0e2\x14.proto.PaymentStatusR\x06status\x12%\n" +
	"\x0etransaction_id\x18\b \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"7\n" +
	"\vPageRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x89\x01\n" +
	"\fPageResponse\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x05R\vcurrentPage\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vtotal_items\x18\x03 \x01(\x05R\n" +
	"totalItems\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"\xd9\x02\n" +
	"\x18CreateApplicationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.proto.ApplicationTypeR\x04type\x12\x1f\n" +
	"\vvehicle_vin\x18\x03 \x01(\tR\n" +
	"vehicleVin\x12!\n" +
	"\fvehicle_name\x18\x04 \x01(\tR\vvehicleName\x12#\n" +
	"\rcurrency_code\x18\x05 \x01(\tR\fcurrencyCode\x12\x1f\n" +
	"\vprice_minor\x18\x06 \x01(\x03R\n" +
	"priceMinor\x12,\n" +
	"\x12down_payment_minor\x18\a \x01(\x03R\x10downPaymentMinor\x12\x1f\n" +
	"\vterm_months\x18\b \x01(\x05R\n" +
	"termMonths\x12\x1f\n" +
	"\vmargin_rate\x18\t \x01(\x01R\n" +
	"marginRate\"\x9c\x01\n" +
	"\x19CreateApplicationResponse\x128\n" +
	"\vapplication\x18\x01 \x01(\v2\x16.proto.LoanApplicationR\vapplication\x12E\n" +
	"\x12loan_service_error\x18d \x01(\v2\x17.proto.LoanServiceErrorR\x10loanServiceError\"'\n" +
	"\x15GetApplicationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x99\x01\n" +
	"\x16GetApplicationResponse\x128\n" +
	"\vapplication\x18\x01 \x01(\v2\x16.proto.LoanApplicationR\vapplication\x12E\n" +
	"\x12loan_service_error\x18d \x01(\v2\x17.proto.LoanServiceErrorR\x10loanServiceError\"Z\n" +
	"\x17ListApplicationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\x04page\x18\x02 \x01(\v2\x12.proto.PageRequestR\x04page\"\xc6\x01\n" +
	"\x18ListApplicationsResponse\x12:\n" +
	"\fapplications\x18\x01 \x03(\v2\x16.proto.LoanApplicationR\fapplications\x12'\n" +
	"\x04page\x18\x02 \x01(\v2\x13.proto.PageResponseR\x04page\x12E\n" +
	"\x12loan_service_error\x18d \x01(\v2\x17.proto.LoanServiceErrorR\x10loanServiceError\"\x15\n" +
	"\x13ListVehiclesRequest\"\x89\x01\n" +
	"\x14ListVehiclesResponse\x12*\n" +
	"\bvehicles\x18\x01 \x03(\v2\x0e.proto.VehicleR\bvehicles\x12E\n" +
	"\x12loan_service_error\x18d \x01(\v2\x17.proto.LoanServiceErrorR\x10loanServiceError\"\xc8\x01\n" +
	"\x10CalculateRequest\x12#\n" +
	"\rcurrency_code\x18\x01 \x01(\tR\fcurrencyCode\x12\x1f\n" +
	"\vprice_minor\x18\x02 \x01(\x03R\n" +
	"priceMinor\x12,\n" +
	"\x12down_payment_minor\x18\x03 \x01(\x03R\x10downPaymentMinor\x12\x1f\n" +
	"\vterm_months\x18\x04 \x01(\x05R\n" +
	"termMonths\x12\x1f\n" +
	"\vmargin_rate\x18\x05 \x01(\x01R\n" +
	"marginRate\"\xe4\x01\n" +
	"\x11CalculateResponse\x12&\n" +
	"\x0fnet_price_minor\x18\x01 \x01(\x03R\rnetPriceMinor\x122\n" +
	"\x15monthly_payment_minor\x18\x02 \x01(\x03R\x13monthlyPaymentMinor\x12,\n" +
	"\x12total_amount_minor\x18\x03 \x01(\x03R\x10totalAmountMinor\x12E\n" +
	"\x12loan_service_error\x18d \x01(\v2\x17.proto.LoanServiceErrorR\x10loanServiceError\" \n" +
	"\x0eGetLoanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"y\n" +
	"\x0fGetLoanResponse\x12\x1f\n" +
	"\x04loan\x18\x01 \x01(\v2\v.proto.LoanR\x04loan\x12E\n" +
	"\x12loan_service_error\x18d \x01(\v2\x17.proto.LoanServiceErrorR\x10loanServiceError\"S\n" +
	"\x10ListLoansRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\x04page\x18\x02 \x01(\v2\x12.proto.PageRequestR\x04page\"\xa6\x01\n" +
	"\x11ListLoansResponse\x12!\n" +
	"\x05loans\x18\x01 \x03(\v2\v.proto.LoanR\x05loans\x12'\n" +
	"\x04page\x18\x02 \x01(\v2\x13.proto.PageResponseR\x04page\x12E\n" +
	"\x12loan_service_error\x18d \x01(\v2\x17.proto.LoanServiceErrorR\x10loanServiceError\"\x9a\x01\n" +
	"\x14CreatePaymentRequest\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\tR\x06loanId\x12#\n" +
	"\rcurrency_code\x18\x02 \x01(\tR\fcurrencyCode\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12,\n" +
	"\x06method\x18\x04 \x01(\x0e2\x14.proto.PaymentMethodR\x06method\"\x88\x01\n" +
	"\x15CreatePaymentResponse\x12(\n" +
	"\apayment\x18\x01 \x01(\v2\x0e.proto.PaymentR\apayment\x12E\n" +
	"\x12loan_service_error\x18d \x01(\v2\x17.proto.LoanServiceErrorR\x10loanServiceError\"V\n" +
	"\x13ListPaymentsRequest\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\tR\x06loanId\x12&\n" +
	"\x04page\x18\x02 \x01(\v2\x12.proto.PageRequestR\x04page\"\xb2\x01\n" +
	"\x14ListPaymentsResponse\x12*\n" +
	"\bpayments\x18\x01 \x03(\v2\x0e.proto.PaymentR\bpayments\x12'\n" +
	"\x04page\x18\x02 \x01(\v2\x13.proto.PageResponseR\x04page\x12E\n" +
	"\x12loan_service_error\x18d \x01(\v2\x17.proto.LoanServiceErrorR\x10loanServiceError*m\n" +
	"\x0fApplicationType\x12 \n" +
	"\x1cAPPLICATION_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15APPLICATION_TYPE_AUTO\x10\x01\x12\x1d\n" +
	"\x19APPLICATION_TYPE_PERSONAL\x10\x02*\xb4\x01\n" +
	"\x11ApplicationStatus\x12\"\n" +
	"\x1eAPPLICATION_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16APPLICATION_STATUS_NEW\x10\x01\x12\x1d\n" +
	"\x19APPLICATION_STATUS_REVIEW\x10\x02\x12\x1f\n" +
	"\x1bAPPLICATION_STATUS_APPROVED\x10\x03\x12\x1f\n" +
	"\x1bAPPLICATION_STATUS_REJECTED\x10\x04*p\n" +
	"\n" +
	"LoanStatus\x12\x1b\n" +
	"\x17LOAN_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12LOAN_STATUS_ACTIVE\x10\x01\x12\x14\n" +
	"\x10LOAN_STATUS_PAID\x10\x02\x12\x17\n" +
	"\x13LOAN_STATUS_OVERDUE\x10\x03*\x96\x01\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PAYMENT_METHOD_WALLET\x10\x01\x12\x17\n" +
	"\x13PAYMENT_METHOD_CARD\x10\x02\x12\x15\n" +
	"\x11PAYMENT_METHOD_QR\x10\x03\x12\x1a\n" +
	"\x16PAYMENT_METHOD_AUTOPAY\x10\x04*\x84\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18PAYMENT_STATUS_CONFIRMED\x10\x02\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x032\xa2\x05\n" +
	"\fLoansService\x12V\n" +
	"\x11CreateApplication\x12\x1f.proto.CreateApplicationRequest\x1a .proto.CreateApplicationResponse\x12M\n" +
	"\x0eGetApplication\x12\x1c.proto.GetApplicationRequest\x1a\x1d.proto.GetApplicationResponse\x12S\n" +
	"\x10ListApplications\x12\x1e.proto.ListApplicationsRequest\x1a\x1f.proto.ListApplicationsResponse\x12G\n" +
	"\fListVehicles\x12\x1a.proto.ListVehiclesRequest\x1a\x1b.proto.ListVehiclesResponse\x12>\n" +
	"\tCalculate\x12\x17.proto.CalculateRequest\x1a\x18.proto.CalculateResponse\x128\n" +
	"\aGetLoan\x12\x15.proto.GetLoanRequest\x1a\x16.proto.GetLoanResponse\x12>\n" +
	"\tListLoans\x12\x17.proto.ListLoansRequest\x1a\x18.proto.ListLoansResponse\x12J\n" +
	"\rCreatePayment\x12\x1b.proto.CreatePaymentRequest\x1a\x1c.proto.CreatePaymentResponse\x12G\n" +
	"\fListPayments\x12\x1a.proto.ListPaymentsRequest\x1a\x1b.proto.ListPaymentsResponseB\x10Z\x0einternal/protob\x06proto3"

var (
	file_internal_proto_loan_service_proto_rawDescOnce sync.Once
	file_internal_proto_loan_service_proto_rawDescData []byte
)

func file_internal_proto_loan_service_proto_rawDescGZIP() []byte {
	file_internal_proto_loan_service_proto_rawDescOnce.Do(func() {
		file_internal_proto_loan_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_loan_service_proto_rawDesc), len(file_internal_proto_loan_service_proto_rawDesc)))
	})
	return file_internal_proto_loan_service_proto_rawDescData
}

var file_internal_proto_loan_service_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_internal_proto_loan_service_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_internal_proto_loan_service_proto_goTypes = []any{
	(ApplicationType)(0),              // 0: proto.ApplicationType
	(ApplicationStatus)(0),            // 1: proto.ApplicationStatus
	(LoanStatus)(0),                   // 2: proto.LoanStatus
	(PaymentMethod)(0),                // 3: proto.PaymentMethod
	(PaymentStatus)(0),                // 4: proto.PaymentStatus
	(*LoanServiceError)(nil),          // 5: proto.LoanServiceError
	(*Vehicle)(nil),                   // 6: proto.Vehicle
	(*LoanApplication)(nil),           // 7: proto.LoanApplication
	(*Loan)(nil),                      // 8: proto.Loan
	(*Payment)(nil),                   // 9: proto.Payment
	(*PageRequest)(nil),               // 10: proto.PageRequest
	(*PageResponse)(nil),              // 11: proto.PageResponse
	(*CreateApplicationRequest)(nil),  // 12: proto.CreateApplicationRequest
	(*CreateApplicationResponse)(nil), // 13: proto.CreateApplicationResponse
	(*GetApplicationRequest)(nil),     // 14: proto.GetApplicationRequest
	(*GetApplicationResponse)(nil),    // 15: proto.GetApplicationResponse
	(*ListApplicationsRequest)(nil),   // 16: proto.ListApplicationsRequest
	(*ListApplicationsResponse)(nil),  // 17: proto.ListApplicationsResponse
	(*ListVehiclesRequest)(nil),       // 18: proto.ListVehiclesRequest
	(*ListVehiclesResponse)(nil),      // 19: proto.ListVehiclesResponse
	(*CalculateRequest)(nil),          // 20: proto.CalculateRequest
	(*CalculateResponse)(nil),         // 21: proto.CalculateResponse
	(*GetLoanRequest)(nil),            // 22: proto.GetLoanRequest
	(*GetLoanResponse)(nil),           // 23: proto.GetLoanResponse
	(*ListLoansRequest)(nil),          // 24: proto.ListLoansRequest
	(*ListLoansResponse)(nil),         // 25: proto.ListLoansResponse
	(*CreatePaymentRequest)(nil),      // 26: proto.CreatePaymentRequest
	(*CreatePaymentResponse)(nil),     // 27: proto.CreatePaymentResponse
	(*ListPaymentsRequest)(nil),       // 28: proto.ListPaymentsRequest
	(*ListPaymentsResponse)(nil),      // 29: proto.ListPaymentsResponse
}
var file_internal_proto_loan_service_proto_depIdxs = []int32{
	0,  // 0: proto.LoanApplication.type:type_name -> proto.ApplicationType
	1,  // 1: proto.LoanApplication.status:type_name -> proto.ApplicationStatus
	2,  // 2: proto.Loan.status:type_name -> proto.LoanStatus
	3,  // 3: proto.Payment.method:type_name -> proto.PaymentMethod
	4,  // 4: proto.Payment.status:type_name -> proto.PaymentStatus
	0,  // 5: proto.CreateApplicationRequest.type:type_name -> proto.ApplicationType
	7,  // 6: proto.CreateApplicationResponse.application:type_name -> proto.LoanApplication
	5,  // 7: proto.CreateApplicationResponse.loan_service_error:type_name -> proto.LoanServiceError
	7,  // 8: proto.GetApplicationResponse.application:type_name -> proto.LoanApplication
	5,  // 9: proto.GetApplicationResponse.loan_service_error:type_name -> proto.LoanServiceError
	10, // 10: proto.ListApplicationsRequest.page:type_name -> proto.PageRequest
	7,  // 11: proto.ListApplicationsResponse.applications:type_name -> proto.LoanApplication
	11, // 12: proto.ListApplicationsResponse.page:type_name -> proto.PageResponse
	5,  // 13: proto.ListApplicationsResponse.loan_service_error:type_name -> proto.LoanServiceError
	6,  // 14: proto.ListVehiclesResponse.vehicles:type_name -> proto.Vehicle
	5,  // 15: proto.ListVehiclesResponse.loan_service_error:type_name -> proto.LoanServiceError
	5,  // 16: proto.CalculateResponse.loan_service_error:type_name -> proto.LoanServiceError
	8,  // 17: proto.GetLoanResponse.loan:type_name -> proto.Loan
	5,  // 18: proto.GetLoanResponse.loan_service_error:type_name -> proto.LoanServiceError
	10, // 19: proto.ListLoansRequest.page:type_name -> proto.PageRequest
	8,  // 20: proto.ListLoansResponse.loans:type_name -> proto.Loan
	11, // 21: proto.ListLoansResponse.page:type_name -> proto.PageResponse
	5,  // 22: proto.ListLoansResponse.loan_service_error:type_name -> proto.LoanServiceError
	3,  // 23: proto.CreatePaymentRequest.method:type_name -> proto.PaymentMethod
	9,  // 24: proto.CreatePaymentResponse.payment:type_name -> proto.Payment
	5,  // 25: proto.CreatePaymentResponse.loan_service_error:type_name -> proto.LoanServiceError
	10, // 26: proto.ListPaymentsRequest.page:type_name -> proto.PageRequest
	9,  // 27: proto.ListPaymentsResponse.payments:type_name -> proto.Payment
	11, // 28: proto.ListPaymentsResponse.page:type_name -> proto.PageResponse
	5,  // 29: proto.ListPaymentsResponse.loan_service_error:type_name -> proto.LoanServiceError
	12, // 30: proto.LoansService.CreateApplication:input_type -> proto.CreateApplicationRequest
	14, // 31: proto.LoansService.GetApplication:input_type -> proto.GetApplicationRequest
	16, // 32: proto.LoansService.ListApplications:input_type -> proto.ListApplicationsRequest
	18, // 33: proto.LoansService.ListVehicles:input_type -> proto.ListVehiclesRequest
	20, // 34: proto.LoansService.Calculate:input_type -> proto.CalculateRequest
	22, // 35: proto.LoansService.GetLoan:input_type -> proto.GetLoanRequest
	24, // 36: proto.LoansService.ListLoans:input_type -> proto.ListLoansRequest
	26, // 37: proto.LoansService.CreatePayment:input_type -> proto.CreatePaymentRequest
	28, // 38: proto.LoansService.ListPayments:input_type -> proto.ListPaymentsRequest
	13, // 39: proto.LoansService.CreateApplication:output_type -> proto.CreateApplicationResponse
	15, // 40: proto.LoansService.GetApplication:output_type -> proto.GetApplicationResponse
	17, // 41: proto.LoansService.ListApplications:output_type -> proto.ListApplicationsResponse
	19, // 42: proto.LoansService.ListVehicles:output_type -> proto.ListVehiclesResponse
	21, // 43: proto.LoansService.Calculate:output_type -> proto.CalculateResponse
	23, // 44: proto.LoansService.GetLoan:output_type -> proto.GetLoanResponse
	25, // 45: proto.LoansService.ListLoans:output_type -> proto.ListLoansResponse
	27, // 46: proto.LoansService.CreatePayment:output_type -> proto.CreatePaymentResponse
	29, // 47: proto.LoansService.ListPayments:output_type -> proto.ListPaymentsResponse
	39, // [39:48] is the sub-list for method output_type
	30, // [30:39] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_internal_proto_loan_service_proto_init() }
func file_internal_proto_loan_service_proto_init() {
	if File_internal_proto_loan_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_loan_service_proto_rawDesc), len(file_internal_proto_loan_service_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_loan_service_proto_goTypes,
		DependencyIndexes: file_internal_proto_loan_service_proto_depIdxs,
		EnumInfos:         file_internal_proto_loan_service_proto_enumTypes,
		MessageInfos:      file_internal_proto_loan_service_proto_msgTypes,
	}.Build()
	File_internal_proto_loan_service_proto = out.File
	file_internal_proto_loan_service_proto_goTypes = nil
	file_internal_proto_loan_service_proto_depIdxs = nil
}
