// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: loans.sql

package repository

import (
	"context"
)

const countLoansByUser = `-- name: CountLoansByUser :one
select count(*)
from loans
where user_id = $1 and status = 'ACTIVE'
`

func (q *Queries) CountLoansByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLoansByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLoan = `-- name: GetLoan :one
select id, application_id, user_id, vehicle_vin, currency_code, amount, term_months, monthly_payment, remaining_balance, status, created_at
from loans
where id = $1
`

func (q *Queries) GetLoan(ctx context.Context, id int64) (Loan, error) {
	row := q.db.QueryRow(ctx, getLoan, id)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.UserID,
		&i.VehicleVin,
		&i.CurrencyCode,
		&i.Amount,
		&i.TermMonths,
		&i.MonthlyPayment,
		&i.RemainingBalance,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listLoansByUser = `-- name: ListLoansByUser :many
select id, application_id, user_id, vehicle_vin, currency_code, amount, term_months, monthly_payment, remaining_balance, status, created_at
from loans
where user_id = $1 and status = 'ACTIVE'
order by id desc
limit $2
offset $3
`

type ListLoansByUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLoansByUser(ctx context.Context, arg ListLoansByUserParams) ([]Loan, error) {
	rows, err := q.db.Query(ctx, listLoansByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loan
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.UserID,
			&i.VehicleVin,
			&i.CurrencyCode,
			&i.Amount,
			&i.TermMonths,
			&i.MonthlyPayment,
			&i.RemainingBalance,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
