// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgtype"
)

type ApplicationStatus string

const (
	ApplicationStatusNEW      ApplicationStatus = "NEW"
	ApplicationStatusREVIEW   ApplicationStatus = "REVIEW"
	ApplicationStatusAPPROVED ApplicationStatus = "APPROVED"
	ApplicationStatusREJECTED ApplicationStatus = "REJECTED"
)

func (e *ApplicationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApplicationStatus(s)
	case string:
		*e = ApplicationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ApplicationStatus: %T", src)
	}
	return nil
}

type NullApplicationStatus struct {
	ApplicationStatus ApplicationStatus `json:"application_status"`
	Valid             bool              `json:"valid"` // Valid is true if ApplicationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApplicationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ApplicationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApplicationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApplicationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApplicationStatus), nil
}

type ApplicationType string

const (
	ApplicationTypeAUTO     ApplicationType = "AUTO"
	ApplicationTypePERSONAL ApplicationType = "PERSONAL"
)

func (e *ApplicationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApplicationType(s)
	case string:
		*e = ApplicationType(s)
	default:
		return fmt.Errorf("unsupported scan type for ApplicationType: %T", src)
	}
	return nil
}

type NullApplicationType struct {
	ApplicationType ApplicationType `json:"application_type"`
	Valid           bool            `json:"valid"` // Valid is true if ApplicationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApplicationType) Scan(value interface{}) error {
	if value == nil {
		ns.ApplicationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApplicationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApplicationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApplicationType), nil
}

type LoanStatus string

const (
	LoanStatusACTIVE  LoanStatus = "ACTIVE"
	LoanStatusPAID    LoanStatus = "PAID"
	LoanStatusOVERDUE LoanStatus = "OVERDUE"
)

func (e *LoanStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LoanStatus(s)
	case string:
		*e = LoanStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LoanStatus: %T", src)
	}
	return nil
}

type NullLoanStatus struct {
	LoanStatus LoanStatus `json:"loan_status"`
	Valid      bool       `json:"valid"` // Valid is true if LoanStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLoanStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LoanStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LoanStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLoanStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LoanStatus), nil
}

type Loan struct {
	ID               int64          `json:"id"`
	ApplicationID    sql.NullInt64  `json:"application_id"`
	UserID           int64          `json:"user_id"`
	VehicleVin       sql.NullString `json:"vehicle_vin"`
	CurrencyCode     string         `json:"currency_code"`
	Amount           pgtype.Numeric `json:"amount"`
	TermMonths       sql.NullInt32  `json:"term_months"`
	MonthlyPayment   pgtype.Numeric `json:"monthly_payment"`
	RemainingBalance pgtype.Numeric `json:"remaining_balance"`
	Status           NullLoanStatus `json:"status"`
	CreatedAt        sql.NullTime   `json:"created_at"`
}

type LoanApplication struct {
	ID             int64                 `json:"id"`
	UserID         int64                 `json:"user_id"`
	Type           ApplicationType       `json:"type"`
	VehicleVin     sql.NullString        `json:"vehicle_vin"`
	VehicleName    sql.NullString        `json:"vehicle_name"`
	CurrencyCode   string                `json:"currency_code"`
	Price          pgtype.Numeric        `json:"price"`
	DownPayment    pgtype.Numeric        `json:"down_payment"`
	NetPrice       pgtype.Numeric        `json:"net_price"`
	MarginRate     pgtype.Numeric        `json:"margin_rate"`
	TermMonths     sql.NullInt32         `json:"term_months"`
	MonthlyPayment pgtype.Numeric        `json:"monthly_payment"`
	Status         NullApplicationStatus `json:"status"`
	CreatedAt      sql.NullTime          `json:"created_at"`
	UpdatedAt      sql.NullTime          `json:"updated_at"`
}

type Payment struct {
	ID            int64          `json:"id"`
	LoanID        sql.NullInt64  `json:"loan_id"`
	PaymentDate   sql.NullTime   `json:"payment_date"`
	Amount        pgtype.Numeric `json:"amount"`
	CurrencyCode  string         `json:"currency_code"`
	Method        sql.NullString `json:"method"`
	Status        sql.NullString `json:"status"`
	TransactionID sql.NullString `json:"transaction_id"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}
