// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type ApplicationStatus string

const (
	ApplicationStatusNEW      ApplicationStatus = "NEW"
	ApplicationStatusREVIEW   ApplicationStatus = "REVIEW"
	ApplicationStatusAPPROVED ApplicationStatus = "APPROVED"
	ApplicationStatusREJECTED ApplicationStatus = "REJECTED"
)

func (e *ApplicationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApplicationStatus(s)
	case string:
		*e = ApplicationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ApplicationStatus: %T", src)
	}
	return nil
}

type NullApplicationStatus struct {
	ApplicationStatus ApplicationStatus `json:"application_status"`
	Valid             bool              `json:"valid"` // Valid is true if ApplicationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApplicationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ApplicationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApplicationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApplicationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApplicationStatus), nil
}

type ApplicationType string

const (
	ApplicationTypeAUTO     ApplicationType = "AUTO"
	ApplicationTypePERSONAL ApplicationType = "PERSONAL"
)

func (e *ApplicationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApplicationType(s)
	case string:
		*e = ApplicationType(s)
	default:
		return fmt.Errorf("unsupported scan type for ApplicationType: %T", src)
	}
	return nil
}

type NullApplicationType struct {
	ApplicationType ApplicationType `json:"application_type"`
	Valid           bool            `json:"valid"` // Valid is true if ApplicationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApplicationType) Scan(value interface{}) error {
	if value == nil {
		ns.ApplicationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApplicationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApplicationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApplicationType), nil
}

type LoanStatus string

const (
	LoanStatusACTIVE  LoanStatus = "ACTIVE"
	LoanStatusPAID    LoanStatus = "PAID"
	LoanStatusOVERDUE LoanStatus = "OVERDUE"
)

func (e *LoanStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LoanStatus(s)
	case string:
		*e = LoanStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LoanStatus: %T", src)
	}
	return nil
}

type NullLoanStatus struct {
	LoanStatus LoanStatus `json:"loan_status"`
	Valid      bool       `json:"valid"` // Valid is true if LoanStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLoanStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LoanStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LoanStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLoanStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LoanStatus), nil
}

type Loan struct {
	ID               int64          `json:"id"`
	ApplicationID    int64          `json:"application_id"`
	UserID           int64          `json:"user_id"`
	VehicleVin       *string        `json:"vehicle_vin"`
	CurrencyCode     string         `json:"currency_code"`
	Amount           *float64       `json:"amount"`
	TermMonths       *int64         `json:"term_months"`
	MonthlyPayment   *float64       `json:"monthly_payment"`
	RemainingBalance *float64       `json:"remaining_balance"`
	Status           NullLoanStatus `json:"status"`
	CreatedAt        *time.Time     `json:"created_at"`
}

type LoanApplication struct {
	ID             int64                 `json:"id"`
	UserID         int64                 `json:"user_id"`
	Type           ApplicationType       `json:"type"`
	VehicleVin     *string               `json:"vehicle_vin"`
	VehicleName    *string               `json:"vehicle_name"`
	CurrencyCode   string                `json:"currency_code"`
	Price          *float64              `json:"price"`
	DownPayment    *float64              `json:"down_payment"`
	NetPrice       *float64              `json:"net_price"`
	MarginRate     *float64              `json:"margin_rate"`
	TermMonths     *int64                `json:"term_months"`
	MonthlyPayment *float64              `json:"monthly_payment"`
	Status         NullApplicationStatus `json:"status"`
	CreatedAt      *time.Time            `json:"created_at"`
	UpdatedAt      *time.Time            `json:"updated_at"`
}
