// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package repository

import (
	"context"
	"time"
)

const countPayments = `-- name: CountPayments :one
select count(*)
from payments
where loan_id = $1
`

func (q *Queries) CountPayments(ctx context.Context, loanID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPayments, loanID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments(
  loan_id,
  currency_code,
  payment_date,
  amount,
  method,
  status,
  transaction_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $6
) RETURNING id, loan_id, payment_date, amount, currency_code, method, status, transaction_id, created_at
`

type CreatePaymentParams struct {
	LoanID       int64      `json:"loan_id"`
	CurrencyCode string     `json:"currency_code"`
	PaymentDate  *time.Time `json:"payment_date"`
	Amount       *float64   `json:"amount"`
	Method       *string    `json:"method"`
	Status       *string    `json:"status"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.LoanID,
		arg.CurrencyCode,
		arg.PaymentDate,
		arg.Amount,
		arg.Method,
		arg.Status,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.PaymentDate,
		&i.Amount,
		&i.CurrencyCode,
		&i.Method,
		&i.Status,
		&i.TransactionID,
		&i.CreatedAt,
	)
	return i, err
}

const listPaymentsByLoan = `-- name: ListPaymentsByLoan :many
select id, loan_id, payment_date, amount, currency_code, method, status, transaction_id, created_at
from payments
where loan_id = $1
order by id desc
limit $2
offset $3
`

type ListPaymentsByLoanParams struct {
	LoanID int64 `json:"loan_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPaymentsByLoan(ctx context.Context, arg ListPaymentsByLoanParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByLoan, arg.LoanID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.LoanID,
			&i.PaymentDate,
			&i.Amount,
			&i.CurrencyCode,
			&i.Method,
			&i.Status,
			&i.TransactionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
