// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/proto/loan/loan_service.proto

package loanpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoanServiceError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanServiceError) Reset() {
	*x = LoanServiceError{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanServiceError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanServiceError) ProtoMessage() {}

func (x *LoanServiceError) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanServiceError.ProtoReflect.Descriptor instead.
func (*LoanServiceError) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{0}
}

func (x *LoanServiceError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoanServiceError) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// -------------------- Core models --------------------
type Vehicle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Vin           string                 `protobuf:"bytes,2,opt,name=vin,proto3" json:"vin,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	EngineType    string                 `protobuf:"bytes,4,opt,name=engine_type,json=engineType,proto3" json:"engine_type,omitempty"`
	Configuration string                 `protobuf:"bytes,5,opt,name=configuration,proto3" json:"configuration,omitempty"`
	Price         int64                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	CurrencyCode  string                 `protobuf:"bytes,7,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"` // "TJS", "USD"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{1}
}

func (x *Vehicle) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Vehicle) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *Vehicle) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Vehicle) GetEngineType() string {
	if x != nil {
		return x.EngineType
	}
	return ""
}

func (x *Vehicle) GetConfiguration() string {
	if x != nil {
		return x.Configuration
	}
	return ""
}

func (x *Vehicle) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Vehicle) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

type LoanApplication struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	VehicleVin     string                 `protobuf:"bytes,4,opt,name=vehicle_vin,json=vehicleVin,proto3" json:"vehicle_vin,omitempty"`
	VehicleName    string                 `protobuf:"bytes,5,opt,name=vehicle_name,json=vehicleName,proto3" json:"vehicle_name,omitempty"`
	CurrencyCode   string                 `protobuf:"bytes,6,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	Price          int64                  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	DownPayment    int64                  `protobuf:"varint,8,opt,name=down_payment,json=downPayment,proto3" json:"down_payment,omitempty"`
	NetPrice       int64                  `protobuf:"varint,9,opt,name=net_price,json=netPrice,proto3" json:"net_price,omitempty"`
	MarginRate     float64                `protobuf:"fixed64,10,opt,name=margin_rate,json=marginRate,proto3" json:"margin_rate,omitempty"`
	TermMonths     int32                  `protobuf:"varint,11,opt,name=term_months,json=termMonths,proto3" json:"term_months,omitempty"`
	MonthlyPayment int64                  `protobuf:"varint,12,opt,name=monthly_payment,json=monthlyPayment,proto3" json:"monthly_payment,omitempty"`
	Status         string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoanApplication) Reset() {
	*x = LoanApplication{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanApplication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanApplication) ProtoMessage() {}

func (x *LoanApplication) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanApplication.ProtoReflect.Descriptor instead.
func (*LoanApplication) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{2}
}

func (x *LoanApplication) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoanApplication) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoanApplication) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LoanApplication) GetVehicleVin() string {
	if x != nil {
		return x.VehicleVin
	}
	return ""
}

func (x *LoanApplication) GetVehicleName() string {
	if x != nil {
		return x.VehicleName
	}
	return ""
}

func (x *LoanApplication) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *LoanApplication) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *LoanApplication) GetDownPayment() int64 {
	if x != nil {
		return x.DownPayment
	}
	return 0
}

func (x *LoanApplication) GetNetPrice() int64 {
	if x != nil {
		return x.NetPrice
	}
	return 0
}

func (x *LoanApplication) GetMarginRate() float64 {
	if x != nil {
		return x.MarginRate
	}
	return 0
}

func (x *LoanApplication) GetTermMonths() int32 {
	if x != nil {
		return x.TermMonths
	}
	return 0
}

func (x *LoanApplication) GetMonthlyPayment() int64 {
	if x != nil {
		return x.MonthlyPayment
	}
	return 0
}

func (x *LoanApplication) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoanApplication) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *LoanApplication) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Loan struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId    string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	UserId           string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrencyCode     string                 `protobuf:"bytes,4,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	VehicleVin       string                 `protobuf:"bytes,5,opt,name=vehicle_vin,json=vehicleVin,proto3" json:"vehicle_vin,omitempty"`
	Amount           int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	TermMonths       int32                  `protobuf:"varint,7,opt,name=term_months,json=termMonths,proto3" json:"term_months,omitempty"`
	MonthlyPayment   int64                  `protobuf:"varint,8,opt,name=monthly_payment,json=monthlyPayment,proto3" json:"monthly_payment,omitempty"`
	RemainingBalance int64                  `protobuf:"varint,9,opt,name=remaining_balance,json=remainingBalance,proto3" json:"remaining_balance,omitempty"`
	Status           string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Loan) Reset() {
	*x = Loan{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Loan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Loan) ProtoMessage() {}

func (x *Loan) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Loan.ProtoReflect.Descriptor instead.
func (*Loan) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{3}
}

func (x *Loan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Loan) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *Loan) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Loan) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *Loan) GetVehicleVin() string {
	if x != nil {
		return x.VehicleVin
	}
	return ""
}

func (x *Loan) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Loan) GetTermMonths() int32 {
	if x != nil {
		return x.TermMonths
	}
	return 0
}

func (x *Loan) GetMonthlyPayment() int64 {
	if x != nil {
		return x.MonthlyPayment
	}
	return 0
}

func (x *Loan) GetRemainingBalance() int64 {
	if x != nil {
		return x.RemainingBalance
	}
	return 0
}

func (x *Loan) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Loan) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LoanId        string                 `protobuf:"bytes,2,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	CurrencyCode  string                 `protobuf:"bytes,3,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	PaymentDate   string                 `protobuf:"bytes,4,opt,name=payment_date,json=paymentDate,proto3" json:"payment_date,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Method        string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	TransactionId string                 `protobuf:"bytes,8,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{4}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

func (x *Payment) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *Payment) GetPaymentDate() string {
	if x != nil {
		return x.PaymentDate
	}
	return ""
}

func (x *Payment) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Payment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{5}
}

func (x *PageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	TotalItems    int32                  `protobuf:"varint,3,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{6}
}

func (x *PageResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *PageResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PageResponse) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *PageResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// Application
type CreateApplicationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	VehicleVin     string                 `protobuf:"bytes,3,opt,name=vehicle_vin,json=vehicleVin,proto3" json:"vehicle_vin,omitempty"`
	VehicleName    string                 `protobuf:"bytes,4,opt,name=vehicle_name,json=vehicleName,proto3" json:"vehicle_name,omitempty"`
	CurrencyCode   string                 `protobuf:"bytes,5,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	Price          int64                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	DownPayment    int64                  `protobuf:"varint,7,opt,name=down_payment,json=downPayment,proto3" json:"down_payment,omitempty"`
	TermMonths     int32                  `protobuf:"varint,8,opt,name=term_months,json=termMonths,proto3" json:"term_months,omitempty"`
	MarginRate     float64                `protobuf:"fixed64,9,opt,name=margin_rate,json=marginRate,proto3" json:"margin_rate,omitempty"`
	NetPrice       int64                  `protobuf:"varint,10,opt,name=net_price,json=netPrice,proto3" json:"net_price,omitempty"`
	MonthlyPayment int64                  `protobuf:"varint,11,opt,name=monthly_payment,json=monthlyPayment,proto3" json:"monthly_payment,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateApplicationRequest) Reset() {
	*x = CreateApplicationRequest{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationRequest) ProtoMessage() {}

func (x *CreateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationRequest.ProtoReflect.Descriptor instead.
func (*CreateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateApplicationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateApplicationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateApplicationRequest) GetVehicleVin() string {
	if x != nil {
		return x.VehicleVin
	}
	return ""
}

func (x *CreateApplicationRequest) GetVehicleName() string {
	if x != nil {
		return x.VehicleName
	}
	return ""
}

func (x *CreateApplicationRequest) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *CreateApplicationRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateApplicationRequest) GetDownPayment() int64 {
	if x != nil {
		return x.DownPayment
	}
	return 0
}

func (x *CreateApplicationRequest) GetTermMonths() int32 {
	if x != nil {
		return x.TermMonths
	}
	return 0
}

func (x *CreateApplicationRequest) GetMarginRate() float64 {
	if x != nil {
		return x.MarginRate
	}
	return 0
}

func (x *CreateApplicationRequest) GetNetPrice() int64 {
	if x != nil {
		return x.NetPrice
	}
	return 0
}

func (x *CreateApplicationRequest) GetMonthlyPayment() int64 {
	if x != nil {
		return x.MonthlyPayment
	}
	return 0
}

type CreateApplicationResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Application      *LoanApplication       `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	LoanServiceError *LoanServiceError      `protobuf:"bytes,100,opt,name=loan_service_error,json=loanServiceError,proto3" json:"loan_service_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateApplicationResponse) Reset() {
	*x = CreateApplicationResponse{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationResponse) ProtoMessage() {}

func (x *CreateApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationResponse.ProtoReflect.Descriptor instead.
func (*CreateApplicationResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateApplicationResponse) GetApplication() *LoanApplication {
	if x != nil {
		return x.Application
	}
	return nil
}

func (x *CreateApplicationResponse) GetLoanServiceError() *LoanServiceError {
	if x != nil {
		return x.LoanServiceError
	}
	return nil
}

type GetApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationRequest) Reset() {
	*x = GetApplicationRequest{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationRequest) ProtoMessage() {}

func (x *GetApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetApplicationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetApplicationResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Application      *LoanApplication       `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	LoanServiceError *LoanServiceError      `protobuf:"bytes,100,opt,name=loan_service_error,json=loanServiceError,proto3" json:"loan_service_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetApplicationResponse) Reset() {
	*x = GetApplicationResponse{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationResponse) ProtoMessage() {}

func (x *GetApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationResponse.ProtoReflect.Descriptor instead.
func (*GetApplicationResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetApplicationResponse) GetApplication() *LoanApplication {
	if x != nil {
		return x.Application
	}
	return nil
}

func (x *GetApplicationResponse) GetLoanServiceError() *LoanServiceError {
	if x != nil {
		return x.LoanServiceError
	}
	return nil
}

type ListApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsRequest) Reset() {
	*x = ListApplicationsRequest{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsRequest) ProtoMessage() {}

func (x *ListApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListApplicationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListApplicationsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListApplicationsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Applications     []*LoanApplication     `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	Page             *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	LoanServiceError *LoanServiceError      `protobuf:"bytes,100,opt,name=loan_service_error,json=loanServiceError,proto3" json:"loan_service_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListApplicationsResponse) Reset() {
	*x = ListApplicationsResponse{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsResponse) ProtoMessage() {}

func (x *ListApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsResponse.ProtoReflect.Descriptor instead.
func (*ListApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListApplicationsResponse) GetApplications() []*LoanApplication {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *ListApplicationsResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListApplicationsResponse) GetLoanServiceError() *LoanServiceError {
	if x != nil {
		return x.LoanServiceError
	}
	return nil
}

type ListVehiclesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesRequest) Reset() {
	*x = ListVehiclesRequest{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesRequest) ProtoMessage() {}

func (x *ListVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesRequest.ProtoReflect.Descriptor instead.
func (*ListVehiclesRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{13}
}

type ListVehiclesResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Vehicles         []*Vehicle             `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	LoanServiceError *LoanServiceError      `protobuf:"bytes,100,opt,name=loan_service_error,json=loanServiceError,proto3" json:"loan_service_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListVehiclesResponse) Reset() {
	*x = ListVehiclesResponse{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesResponse) ProtoMessage() {}

func (x *ListVehiclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesResponse.ProtoReflect.Descriptor instead.
func (*ListVehiclesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListVehiclesResponse) GetVehicles() []*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

func (x *ListVehiclesResponse) GetLoanServiceError() *LoanServiceError {
	if x != nil {
		return x.LoanServiceError
	}
	return nil
}

// Calculator
type CalculateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyCode  string                 `protobuf:"bytes,1,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	DownPayment   int64                  `protobuf:"varint,3,opt,name=down_payment,json=downPayment,proto3" json:"down_payment,omitempty"`
	TermMonths    int32                  `protobuf:"varint,4,opt,name=term_months,json=termMonths,proto3" json:"term_months,omitempty"`
	MarginRate    float64                `protobuf:"fixed64,5,opt,name=margin_rate,json=marginRate,proto3" json:"margin_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateRequest) Reset() {
	*x = CalculateRequest{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRequest) ProtoMessage() {}

func (x *CalculateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRequest.ProtoReflect.Descriptor instead.
func (*CalculateRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{15}
}

func (x *CalculateRequest) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *CalculateRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CalculateRequest) GetDownPayment() int64 {
	if x != nil {
		return x.DownPayment
	}
	return 0
}

func (x *CalculateRequest) GetTermMonths() int32 {
	if x != nil {
		return x.TermMonths
	}
	return 0
}

func (x *CalculateRequest) GetMarginRate() float64 {
	if x != nil {
		return x.MarginRate
	}
	return 0
}

type CalculateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NetPrice         int64                  `protobuf:"varint,1,opt,name=net_price,json=netPrice,proto3" json:"net_price,omitempty"`
	MonthlyPayment   int64                  `protobuf:"varint,2,opt,name=monthly_payment,json=monthlyPayment,proto3" json:"monthly_payment,omitempty"`
	TotalAmount      int64                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	LoanServiceError *LoanServiceError      `protobuf:"bytes,100,opt,name=loan_service_error,json=loanServiceError,proto3" json:"loan_service_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CalculateResponse) Reset() {
	*x = CalculateResponse{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateResponse) ProtoMessage() {}

func (x *CalculateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateResponse.ProtoReflect.Descriptor instead.
func (*CalculateResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{16}
}

func (x *CalculateResponse) GetNetPrice() int64 {
	if x != nil {
		return x.NetPrice
	}
	return 0
}

func (x *CalculateResponse) GetMonthlyPayment() int64 {
	if x != nil {
		return x.MonthlyPayment
	}
	return 0
}

func (x *CalculateResponse) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *CalculateResponse) GetLoanServiceError() *LoanServiceError {
	if x != nil {
		return x.LoanServiceError
	}
	return nil
}

// Loans
type GetLoanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoanRequest) Reset() {
	*x = GetLoanRequest{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanRequest) ProtoMessage() {}

func (x *GetLoanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanRequest.ProtoReflect.Descriptor instead.
func (*GetLoanRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetLoanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetLoanResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Loan             *Loan                  `protobuf:"bytes,1,opt,name=loan,proto3" json:"loan,omitempty"`
	LoanServiceError *LoanServiceError      `protobuf:"bytes,100,opt,name=loan_service_error,json=loanServiceError,proto3" json:"loan_service_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetLoanResponse) Reset() {
	*x = GetLoanResponse{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanResponse) ProtoMessage() {}

func (x *GetLoanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanResponse.ProtoReflect.Descriptor instead.
func (*GetLoanResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetLoanResponse) GetLoan() *Loan {
	if x != nil {
		return x.Loan
	}
	return nil
}

func (x *GetLoanResponse) GetLoanServiceError() *LoanServiceError {
	if x != nil {
		return x.LoanServiceError
	}
	return nil
}

type ListLoansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoansRequest) Reset() {
	*x = ListLoansRequest{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoansRequest) ProtoMessage() {}

func (x *ListLoansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoansRequest.ProtoReflect.Descriptor instead.
func (*ListLoansRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{19}
}

func (x *ListLoansRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListLoansRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListLoansResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Loans            []*Loan                `protobuf:"bytes,1,rep,name=loans,proto3" json:"loans,omitempty"`
	Page             *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	LoanServiceError *LoanServiceError      `protobuf:"bytes,100,opt,name=loan_service_error,json=loanServiceError,proto3" json:"loan_service_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListLoansResponse) Reset() {
	*x = ListLoansResponse{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoansResponse) ProtoMessage() {}

func (x *ListLoansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoansResponse.ProtoReflect.Descriptor instead.
func (*ListLoansResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{20}
}

func (x *ListLoansResponse) GetLoans() []*Loan {
	if x != nil {
		return x.Loans
	}
	return nil
}

func (x *ListLoansResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListLoansResponse) GetLoanServiceError() *LoanServiceError {
	if x != nil {
		return x.LoanServiceError
	}
	return nil
}

// Payments
type ListPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanId        string                 `protobuf:"bytes,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsRequest) Reset() {
	*x = ListPaymentsRequest{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsRequest) ProtoMessage() {}

func (x *ListPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{21}
}

func (x *ListPaymentsRequest) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

func (x *ListPaymentsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListPaymentsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Payments         []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	Page             *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	LoanServiceError *LoanServiceError      `protobuf:"bytes,100,opt,name=loan_service_error,json=loanServiceError,proto3" json:"loan_service_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListPaymentsResponse) Reset() {
	*x = ListPaymentsResponse{}
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsResponse) ProtoMessage() {}

func (x *ListPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_loan_loan_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_loan_loan_service_proto_rawDescGZIP(), []int{22}
}

func (x *ListPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *ListPaymentsResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListPaymentsResponse) GetLoanServiceError() *LoanServiceError {
	if x != nil {
		return x.LoanServiceError
	}
	return nil
}

var File_internal_proto_loan_loan_service_proto protoreflect.FileDescriptor

const file_internal_proto_loan_loan_service_proto_rawDesc = "" +
	"\n" +
	"&internal/proto/loan/loan_service.proto\x12\x06loanpb\"H\n" +
	"\x10LoanServiceError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\xce\x01\n" +
	"\aVehicle\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl\x12\x10\n" +
	"\x03vin\x18\x02 \x01(\tR\x03vin\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vengine_type\x18\x04 \x01(\tR\n" +
	"engineType\x12$\n" +
	"\rconfiguration\x18\x05 \x01(\tR\rconfiguration\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x03R\x05price\x12#\n" +
	"\rcurrency_code\x18\a \x01(\tR\fcurrencyCode\"\xce\x03\n" +
	"\x0fLoanApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1f\n" +
	"\vvehicle_vin\x18\x04 \x01(\tR\n" +
	"vehicleVin\x12!\n" +
	"\fvehicle_name\x18\x05 \x01(\tR\vvehicleName\x12#\n" +
	"\rcurrency_code\x18\x06 \x01(\tR\fcurrencyCode\x12\x14\n" +
	"\x05price\x18\a \x01(\x03R\x05price\x12!\n" +
	"\fdown_payment\x18\b \x01(\x03R\vdownPayment\x12\x1b\n" +
	"\tnet_price\x18\t \x01(\x03R\bnetPrice\x12\x1f\n" +
	"\vmargin_rate\x18\n" +
	" \x01(\x01R\n" +
	"marginRate\x12\x1f\n" +
	"\vterm_months\x18\v \x01(\x05R\n" +
	"termMonths\x12'\n" +
	"\x0fmonthly_payment\x18\f \x01(\x03R\x0emonthlyPayment\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt\"\xe2\x02\n" +
	"\x04Loan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12#\n" +
	"\rcurrency_code\x18\x04 \x01(\tR\fcurrencyCode\x12\x1f\n" +
	"\vvehicle_vin\x18\x05 \x01(\tR\n" +
	"vehicleVin\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\x12\x1f\n" +
	"\vterm_months\x18\a \x01(\x05R\n" +
	"termMonths\x12'\n" +
	"\x0fmonthly_payment\x18\b \x01(\x03R\x0emonthlyPayment\x12+\n" +
	"\x11remaining_balance\x18\t \x01(\x03R\x10remainingBalance\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\"\x88\x02\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aloan_id\x18\x02 \x01(\tR\x06loanId\x12#\n" +
	"\rcurrency_code\x18\x03 \x01(\tR\fcurrencyCode\x12!\n" +
	"\fpayment_date\x18\x04 \x01(\tR\vpaymentDate\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12%\n" +
	"\x0etransaction_id\x18\b \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"7\n" +
	"\vPageRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x89\x01\n" +
	"\fPageResponse\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x05R\vcurrentPage\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vtotal_items\x18\x03 \x01(\x05R\n" +
	"totalItems\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"\xf1\x02\n" +
	"\x18CreateApplicationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1f\n" +
	"\vvehicle_vin\x18\x03 \x01(\tR\n" +
	"vehicleVin\x12!\n" +
	"\fvehicle_name\x18\x04 \x01(\tR\vvehicleName\x12#\n" +
	"\rcurrency_code\x18\x05 \x01(\tR\fcurrencyCode\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x03R\x05price\x12!\n" +
	"\fdown_payment\x18\a \x01(\x03R\vdownPayment\x12\x1f\n" +
	"\vterm_months\x18\b \x01(\x05R\n" +
	"termMonths\x12\x1f\n" +
	"\vmargin_rate\x18\t \x01(\x01R\n" +
	"marginRate\x12\x1b\n" +
	"\tnet_price\x18\n" +
	" \x01(\x03R\bnetPrice\x12'\n" +
	"\x0fmonthly_payment\x18\v \x01(\x03R\x0emonthlyPayment\"\x9e\x01\n" +
	"\x19CreateApplicationResponse\x129\n" +
	"\vapplication\x18\x01 \x01(\v2\x17.loanpb.LoanApplicationR\vapplication\x12F\n" +
	"\x12loan_service_error\x18d \x01(\v2\x18.loanpb.LoanServiceErrorR\x10loanServiceError\"'\n" +
	"\x15GetApplicationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9b\x01\n" +
	"\x16GetApplicationResponse\x129\n" +
	"\vapplication\x18\x01 \x01(\v2\x17.loanpb.LoanApplicationR\vapplication\x12F\n" +
	"\x12loan_service_error\x18d \x01(\v2\x18.loanpb.LoanServiceErrorR\x10loanServiceError\"[\n" +
	"\x17ListApplicationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x04page\x18\x02 \x01(\v2\x13.loanpb.PageRequestR\x04page\"\xc9\x01\n" +
	"\x18ListApplicationsResponse\x12;\n" +
	"\fapplications\x18\x01 \x03(\v2\x17.loanpb.LoanApplicationR\fapplications\x12(\n" +
	"\x04page\x18\x02 \x01(\v2\x14.loanpb.PageResponseR\x04page\x12F\n" +
	"\x12loan_service_error\x18d \x01(\v2\x18.loanpb.LoanServiceErrorR\x10loanServiceError\"\x15\n" +
	"\x13ListVehiclesRequest\"\x8b\x01\n" +
	"\x14ListVehiclesResponse\x12+\n" +
	"\bvehicles\x18\x01 \x03(\v2\x0f.loanpb.VehicleR\bvehicles\x12F\n" +
	"\x12loan_service_error\x18d \x01(\v2\x18.loanpb.LoanServiceErrorR\x10loanServiceError\"\xb2\x01\n" +
	"\x10CalculateRequest\x12#\n" +
	"\rcurrency_code\x18\x01 \x01(\tR\fcurrencyCode\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05price\x12!\n" +
	"\fdown_payment\x18\x03 \x01(\x03R\vdownPayment\x12\x1f\n" +
	"\vterm_months\x18\x04 \x01(\x05R\n" +
	"termMonths\x12\x1f\n" +
	"\vmargin_rate\x18\x05 \x01(\x01R\n" +
	"marginRate\"\xc4\x01\n" +
	"\x11CalculateResponse\x12\x1b\n" +
	"\tnet_price\x18\x01 \x01(\x03R\bnetPrice\x12'\n" +
	"\x0fmonthly_payment\x18\x02 \x01(\x03R\x0emonthlyPayment\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x03R\vtotalAmount\x12F\n" +
	"\x12loan_service_error\x18d \x01(\v2\x18.loanpb.LoanServiceErrorR\x10loanServiceError\" \n" +
	"\x0eGetLoanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"{\n" +
	"\x0fGetLoanResponse\x12 \n" +
	"\x04loan\x18\x01 \x01(\v2\f.loanpb.LoanR\x04loan\x12F\n" +
	"\x12loan_service_error\x18d \x01(\v2\x18.loanpb.LoanServiceErrorR\x10loanServiceError\"T\n" +
	"\x10ListLoansRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x04page\x18\x02 \x01(\v2\x13.loanpb.PageRequestR\x04page\"\xa9\x01\n" +
	"\x11ListLoansResponse\x12\"\n" +
	"\x05loans\x18\x01 \x03(\v2\f.loanpb.LoanR\x05loans\x12(\n" +
	"\x04page\x18\x02 \x01(\v2\x14.loanpb.PageResponseR\x04page\x12F\n" +
	"\x12loan_service_error\x18d \x01(\v2\x18.loanpb.LoanServiceErrorR\x10loanServiceError\"W\n" +
	"\x13ListPaymentsRequest\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\tR\x06loanId\x12'\n" +
	"\x04page\x18\x02 \x01(\v2\x13.loanpb.PageRequestR\x04page\"\xb5\x01\n" +
	"\x14ListPaymentsResponse\x12+\n" +
	"\bpayments\x18\x01 \x03(\v2\x0f.loanpb.PaymentR\bpayments\x12(\n" +
	"\x04page\x18\x02 \x01(\v2\x14.loanpb.PageResponseR\x04page\x12F\n" +
	"\x12loan_service_error\x18d \x01(\v2\x18.loanpb.LoanServiceErrorR\x10loanServiceError2\xe6\x04\n" +
	"\fLoansService\x12X\n" +
	"\x11CreateApplication\x12 .loanpb.CreateApplicationRequest\x1a!.loanpb.CreateApplicationResponse\x12O\n" +
	"\x0eGetApplication\x12\x1d.loanpb.GetApplicationRequest\x1a\x1e.loanpb.GetApplicationResponse\x12U\n" +
	"\x10ListApplications\x12\x1f.loanpb.ListApplicationsRequest\x1a .loanpb.ListApplicationsResponse\x12I\n" +
	"\fListVehicles\x12\x1b.loanpb.ListVehiclesRequest\x1a\x1c.loanpb.ListVehiclesResponse\x12@\n" +
	"\tCalculate\x12\x18.loanpb.CalculateRequest\x1a\x19.loanpb.CalculateResponse\x12:\n" +
	"\aGetLoan\x12\x16.loanpb.GetLoanRequest\x1a\x17.loanpb.GetLoanResponse\x12@\n" +
	"\tListLoans\x12\x18.loanpb.ListLoansRequest\x1a\x19.loanpb.ListLoansResponse\x12I\n" +
	"\fListPayments\x12\x1b.loanpb.ListPaymentsRequest\x1a\x1c.loanpb.ListPaymentsResponseB\x17Z\x15internal/proto/loanpbb\x06proto3"

var (
	file_internal_proto_loan_loan_service_proto_rawDescOnce sync.Once
	file_internal_proto_loan_loan_service_proto_rawDescData []byte
)

func file_internal_proto_loan_loan_service_proto_rawDescGZIP() []byte {
	file_internal_proto_loan_loan_service_proto_rawDescOnce.Do(func() {
		file_internal_proto_loan_loan_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_loan_loan_service_proto_rawDesc), len(file_internal_proto_loan_loan_service_proto_rawDesc)))
	})
	return file_internal_proto_loan_loan_service_proto_rawDescData
}

var file_internal_proto_loan_loan_service_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_internal_proto_loan_loan_service_proto_goTypes = []any{
	(*LoanServiceError)(nil),          // 0: loanpb.LoanServiceError
	(*Vehicle)(nil),                   // 1: loanpb.Vehicle
	(*LoanApplication)(nil),           // 2: loanpb.LoanApplication
	(*Loan)(nil),                      // 3: loanpb.Loan
	(*Payment)(nil),                   // 4: loanpb.Payment
	(*PageRequest)(nil),               // 5: loanpb.PageRequest
	(*PageResponse)(nil),              // 6: loanpb.PageResponse
	(*CreateApplicationRequest)(nil),  // 7: loanpb.CreateApplicationRequest
	(*CreateApplicationResponse)(nil), // 8: loanpb.CreateApplicationResponse
	(*GetApplicationRequest)(nil),     // 9: loanpb.GetApplicationRequest
	(*GetApplicationResponse)(nil),    // 10: loanpb.GetApplicationResponse
	(*ListApplicationsRequest)(nil),   // 11: loanpb.ListApplicationsRequest
	(*ListApplicationsResponse)(nil),  // 12: loanpb.ListApplicationsResponse
	(*ListVehiclesRequest)(nil),       // 13: loanpb.ListVehiclesRequest
	(*ListVehiclesResponse)(nil),      // 14: loanpb.ListVehiclesResponse
	(*CalculateRequest)(nil),          // 15: loanpb.CalculateRequest
	(*CalculateResponse)(nil),         // 16: loanpb.CalculateResponse
	(*GetLoanRequest)(nil),            // 17: loanpb.GetLoanRequest
	(*GetLoanResponse)(nil),           // 18: loanpb.GetLoanResponse
	(*ListLoansRequest)(nil),          // 19: loanpb.ListLoansRequest
	(*ListLoansResponse)(nil),         // 20: loanpb.ListLoansResponse
	(*ListPaymentsRequest)(nil),       // 21: loanpb.ListPaymentsRequest
	(*ListPaymentsResponse)(nil),      // 22: loanpb.ListPaymentsResponse
}
var file_internal_proto_loan_loan_service_proto_depIdxs = []int32{
	2,  // 0: loanpb.CreateApplicationResponse.application:type_name -> loanpb.LoanApplication
	0,  // 1: loanpb.CreateApplicationResponse.loan_service_error:type_name -> loanpb.LoanServiceError
	2,  // 2: loanpb.GetApplicationResponse.application:type_name -> loanpb.LoanApplication
	0,  // 3: loanpb.GetApplicationResponse.loan_service_error:type_name -> loanpb.LoanServiceError
	5,  // 4: loanpb.ListApplicationsRequest.page:type_name -> loanpb.PageRequest
	2,  // 5: loanpb.ListApplicationsResponse.applications:type_name -> loanpb.LoanApplication
	6,  // 6: loanpb.ListApplicationsResponse.page:type_name -> loanpb.PageResponse
	0,  // 7: loanpb.ListApplicationsResponse.loan_service_error:type_name -> loanpb.LoanServiceError
	1,  // 8: loanpb.ListVehiclesResponse.vehicles:type_name -> loanpb.Vehicle
	0,  // 9: loanpb.ListVehiclesResponse.loan_service_error:type_name -> loanpb.LoanServiceError
	0,  // 10: loanpb.CalculateResponse.loan_service_error:type_name -> loanpb.LoanServiceError
	3,  // 11: loanpb.GetLoanResponse.loan:type_name -> loanpb.Loan
	0,  // 12: loanpb.GetLoanResponse.loan_service_error:type_name -> loanpb.LoanServiceError
	5,  // 13: loanpb.ListLoansRequest.page:type_name -> loanpb.PageRequest
	3,  // 14: loanpb.ListLoansResponse.loans:type_name -> loanpb.Loan
	6,  // 15: loanpb.ListLoansResponse.page:type_name -> loanpb.PageResponse
	0,  // 16: loanpb.ListLoansResponse.loan_service_error:type_name -> loanpb.LoanServiceError
	5,  // 17: loanpb.ListPaymentsRequest.page:type_name -> loanpb.PageRequest
	4,  // 18: loanpb.ListPaymentsResponse.payments:type_name -> loanpb.Payment
	6,  // 19: loanpb.ListPaymentsResponse.page:type_name -> loanpb.PageResponse
	0,  // 20: loanpb.ListPaymentsResponse.loan_service_error:type_name -> loanpb.LoanServiceError
	7,  // 21: loanpb.LoansService.CreateApplication:input_type -> loanpb.CreateApplicationRequest
	9,  // 22: loanpb.LoansService.GetApplication:input_type -> loanpb.GetApplicationRequest
	11, // 23: loanpb.LoansService.ListApplications:input_type -> loanpb.ListApplicationsRequest
	13, // 24: loanpb.LoansService.ListVehicles:input_type -> loanpb.ListVehiclesRequest
	15, // 25: loanpb.LoansService.Calculate:input_type -> loanpb.CalculateRequest
	17, // 26: loanpb.LoansService.GetLoan:input_type -> loanpb.GetLoanRequest
	19, // 27: loanpb.LoansService.ListLoans:input_type -> loanpb.ListLoansRequest
	21, // 28: loanpb.LoansService.ListPayments:input_type -> loanpb.ListPaymentsRequest
	8,  // 29: loanpb.LoansService.CreateApplication:output_type -> loanpb.CreateApplicationResponse
	10, // 30: loanpb.LoansService.GetApplication:output_type -> loanpb.GetApplicationResponse
	12, // 31: loanpb.LoansService.ListApplications:output_type -> loanpb.ListApplicationsResponse
	14, // 32: loanpb.LoansService.ListVehicles:output_type -> loanpb.ListVehiclesResponse
	16, // 33: loanpb.LoansService.Calculate:output_type -> loanpb.CalculateResponse
	18, // 34: loanpb.LoansService.GetLoan:output_type -> loanpb.GetLoanResponse
	20, // 35: loanpb.LoansService.ListLoans:output_type -> loanpb.ListLoansResponse
	22, // 36: loanpb.LoansService.ListPayments:output_type -> loanpb.ListPaymentsResponse
	29, // [29:37] is the sub-list for method output_type
	21, // [21:29] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_internal_proto_loan_loan_service_proto_init() }
func file_internal_proto_loan_loan_service_proto_init() {
	if File_internal_proto_loan_loan_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_loan_loan_service_proto_rawDesc), len(file_internal_proto_loan_loan_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_loan_loan_service_proto_goTypes,
		DependencyIndexes: file_internal_proto_loan_loan_service_proto_depIdxs,
		MessageInfos:      file_internal_proto_loan_loan_service_proto_msgTypes,
	}.Build()
	File_internal_proto_loan_loan_service_proto = out.File
	file_internal_proto_loan_loan_service_proto_goTypes = nil
	file_internal_proto_loan_loan_service_proto_depIdxs = nil
}
